### ISSUE TITLE
Fix nested function calls in the forward mode

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#116]
At the moment, calls in the forward mode work correctly only if called function has one input.
If a function `f` is called with args `a1, a2, ...`, its derivative should be a dot product of `gradient(f)(a1, a2, ...)` and a vector of derivatives of args: `{ da1, da2, ...}`.

This dot product can be efficiently computed by differentiating `f` in the forward mode and providing values of `da1, da2, ...` as seeds. See issue #100.

**Comment by vaithak** [comment]
Similar to #100, this was fixed in https://github.com/vgvassilev/clad/pull/565 and many subsequent PRs which added the vector forward mode support.

We also have many test cases present with the vector mode interface: https://github.com/vgvassilev/clad/blob/master/test/ForwardMode/VectorMode.C.
Demo example: https://github.com/vgvassilev/clad/blob/master/demos/VectorForwardMode.cpp

**Comment by vgvassilev** [comment]
Thanks @vaithak, let's close the issue now.
