### ISSUE TITLE
How to support tensor?

### ISSUE THREAD

**Issue by FDInSky** [vgvassilev/clad#169]

**Comment by vgvassilev** [comment]
Thanks for reaching out!

Can you give an example of what exactly you have in mind?

**Comment by parth-07** [comment]
Clad already supports basic classes, member function calls and operator overloads in both the forward-mode AD and the reverse-mode AD. There are some tests for class-type supports (including a test for Tensor) in `test/ForwardMode/UserDefinedTypes.C` and `test/Gradient/UserDefinedTypes.C`. I am closing this issue for now because the issue does not mention any specific feature that needs to be supported.
