### ISSUE TITLE
forward declaration usage doesn't work 

### ISSUE THREAD

**Issue by beautiful-mind** [vgvassilev/clad#30]
double pow(double x);
then pow_dx(4.2); does not work. execute and funtionpointer usage work.

**Comment by beautiful-mind** [comment]
I will like to ask author of DerivativeBuilder.cpp that do you remember why it's kept so. Do you remember any problem you got getting rid of this

**Comment by vgvassilev** [comment]
@beautiful-mind, @mvassilev  should be able to answer your question.

**Comment by mvassilev** [comment]
Hi @beautiful-mind,

The naming style of the derived functions (and the other c++ constructs) is changed and names like <function_name>_dx are no longer generated. Now the naming pattern in use is <function_name>_darg0 in case you request the first deivative with respect to the first argument, <function_name>_d2arg1 in case you request the second order derivative with respect to the second argument and so on. We think this naming pattern is more generic and expresses better how this function was generated.

The reason why this code does not run is because it is compiled only with -fsyntax-only. Pull request are more than welcome so feel free to submit one addressing this issue.

Martin

**Comment by vgvassilev** [comment]
I'd consider that answered and resolved.
