### ISSUE TITLE
Passing a runtime value as a second parameter of clad::differentiate results in error

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#38]
For example
```
int i = 0;
clad::differentiate(f, i);
```
will result in 
**error: Must be an integral value**,

whereas 
```
clad::differentiate(f, 0);
```
will work.

This is not necessarily a problem but it is somewhat misleading.

**Comment by gojakuch** [comment]
I don't think it's a problem at all, since Clad works at compile time and cannot operate with such values as arguments. const-expressions, on the other hand, work well as arguments, so there's nothing more to do here. moreover, the current error it throws actually explains that this argument should be a literal, so it's quite user-friendly.
