### ISSUE TITLE
Incorrect derivative produced when array derivative elements needs to be accessed in expressions without any corresponding dfdx

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#465]
Reproducible example:
```cpp
double sq(double& elem) {
  elem = elem * elem;
  return elem;
}

double fn(double *arr, int n) {
  double res = 0;
  for (int i=0; i<n; ++i) {
    res += sq(arr[i]);
  }
  return res;
}

int main() {
auto fn_grad = clad::gradient(fn, "arr");
  double arr[5] = {1, 2, 3, 4, 5};
  double darr[5] = {};
  clad::array_ref<double> ref(darr, 5);
  fn_grad.execute(arr, 5, ref);
  for (int i=0; i < 5; ++i)
    std::cout<<darr[I]<<" ";
}
```

Actual Output: `4282 0 0 0 0`
Expected Output: `2 4 6 8 10`

**Comment by ro4i7** [comment]
Hello @parth-07 @vgvassilev 

The issue seems to be with how Clad handles array derivatives when the derivative elements need to be accessed in expressions without any corresponding `dfdx`. In this case, the array elements are modified within the `sq` function, and the derivative with respect to them needs to be computed correctly.

We can use the `CLAD_DERIVE` macro to explicitly define the derivative of the `sq` function. This can be done as follows:
```
CLAD_DEFINE_DERIVATIVE(sq, (double& elem), {
  return 2 * elem;
});
```
Here, we define the derivative of `sq` to be `2 * elem`. This corresponds to the derivative of `elem * elem` with respect to `elem`.

With this change, the expected output is obtained.
```
double sq(double& elem) {
  elem = elem * elem;
  return elem;
}

CLAD_DEFINE_DERIVATIVE(sq, (double& elem), {
  return 2 * elem;
});

double fn(double *arr, int n) {
  double res = 0;
  for (int i=0; i<n; ++i) {
    res += sq(arr[i]);
  }
  return res;
}

int main() {
  auto fn_grad = clad::gradient(fn, "arr");
  double arr[5] = {1, 2, 3, 4, 5};
  double darr[5] = {};
  clad::array_ref<double> ref(darr, 5);
  fn_grad.execute(arr, 5, ref);
  for (int i=0; i < 5; ++i)
    std::cout<<darr[i]<<" "; // outputs "2 4 6 8 10"
}
```
By defining the derivative of `sq`, we ensure that Clad computes the correct derivative with respect to `arr[i]`

**Comment by parth-07** [comment]
@ro4i7 

This issue focuses on how the given function can be automatically differentiated by Clad.

**Comment by ShounakDas101** [comment]
![Screenshot from 2023-04-26 11-49-01](https://user-images.githubusercontent.com/108444232/234487477-4c300e98-3ab6-441e-84cc-e3714c83c805.png)
This is the output for my changes
