### ISSUE TITLE
Contribution guide hyperlink in README.md is broken.

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#506]
Under the section, [How to Contibute](https://github.com/vgvassilev/clad#how-to-contribute), Clad provides _contribution guide_ hyperlink. This hyperlink is broken. Two (of the many) places where we can add contributing information are:

- CONTRIBUTING.md file in the repository.
- [Developer's Documentation](https://clad.readthedocs.io/en/latest/user/DevelopersDocumentation.html)

**Comment by ioanaif** [comment]
@vgvassilev 

The link is broken because there is no url added. 

[Developer's Documentation](https://clad.readthedocs.io/en/latest/user/DevelopersDocumentation.html) explains in detail how to build Clad from source and how to debug Clang. 

Do you want to just fix the README hyperlink to point to this or do you want other contribution details to be added to this page?
