### ISSUE TITLE
clang just return non zero return code and produces nothing

### ISSUE THREAD

**Issue by ipcamit** [vgvassilev/clad#529]
I am using clang 12.0.1 pre-built binary compilers, with clad compiled from source.
When I try to compile the first example my shell just indicates non-zero return error and there are no binary artifacts present (see below). 
What I am doing wrong?
![image](https://user-images.githubusercontent.com/6790415/218374964-0a86bbe5-c9b6-4d75-a22b-c20eb57060d6.png)

**Comment by parth-07** [comment]
Hi @ipcamit,
Using `clang -cc1` is generally difficult to get right because you have to manually pass the correct standard library paths and compiler options.

I would suggest you to explicitly pass options to the clang compiler from clang driver using `-Xclang` option. You can use the command shown below to compile the program and run Clad:

```
clang++ -o main.elf main.cpp -Xclang -add-plugin -Xclang clad -Xclang -load -Xclang /path/to/clad.so -I/path/to/clad/include -xc++
```

**Comment by ipcamit** [comment]
Thanks it worked with your suggestion.
