### ISSUE TITLE
Feature request: Support for higher order functions

### ISSUE THREAD

**Issue by guitargeek** [vgvassilev/clad#637]
It would be very nice if differentiating through higher order functions would work also in Clad.

It happens often that one has an algorithm that is implemented in a header-only library, where one or the parameters is a function.

This would be relevant for example when using the numeric integration algorithms from ROOT/RooFit inside a function that one wants to differentiate with Clad.

Here is an example of what I such a pattern would look like:

```c++
// Compile with clang++ -std=c++11 -fplugin=/usr/lib/clad.so cladNestedFuncs.cxx -o cladNestedFuncs

#include "clad/Differentiator/Differentiator.h"

#include <iostream>
#include <vector>

// Supporting templates would also be good (in fact even better for my usecase)
// template<class Func>
// double algo(Func func, double x) {}
double algo(double (*func)(double), double x)
{
   double val = func(x);
   return val * val;
}

double func(double x)
{
   return x + 1;
}

double wrapper(double *params)
{
   return algo(func, params[0]);
}

int main()
{
   double x = 2.0;
   std::cout << wrapper(&x) << std::endl;

   auto grad = clad::gradient(wrapper, "params");

   double result = 0.0;
   grad.execute(&x, &result);

   std::cout << result << std::endl;
}
```

Or maybe I missed that there is already an existing solution for this?

Thank you very much for considering this!

**Comment by parth-07** [comment]
Hi @guitargeek,

Thank you for opening this feature request. It's an interesting feature. But sadly, it cannot be supported in Clad.
Not just Clad, this feature actually cannot be supported in any traditional source transformation AD tool.

Source transformation AD tools depend on the function source to be available at compile-time. When function pointers
are involved, then the complete function source code is not available at compile-time :'). More concretely, the source code for the`func` is not available at compile-time, in the example shown below: 

```cpp
double algo(double (*func)(double), double x)
{
   double val = func(x);
   return val * val;
}
```
`func` derivative function cannot be generated because `func` value is only known at runtime and Clad (and all other source transformation tools) works entirely at compile-time. The `algo` function cannot be differentiated because `func` cannot be differentiated.

That being said, we can have workarounds to solve this problem. With some modifications in Clad, we can achieve 
something like the program shown below:

```cpp
double algo(double (*func)(double), double x)
{
   double val = func(x);
   return val * val;
}

auto grad = clad::gradient(algo);
double x;
double dx = 0;
auto grad_func = clad::gradient(func);
grad.execute(func, x, grad_func, &dx);
```
@guitargeek What do you think about this? We can support `wrapper` function by extending this idea.

--------------------------------

Also, what do you think about using functor objects instead of functions? For example:

```cpp
template<class Functor>
double algo(Functor functor, double x)
{
   double val = functor(x);
   return val * val;
}
```

This code can be differentiated at compile-time (barring some bugs in Clad). It can be differentiated at compile-time
because `Functor` has to be known at compile-time, therefore the `Functor::operator()` function source code is also
available at compile-time.

**Comment by guitargeek** [comment]
Hi, thank you very much for your reply!

That's great news, since I actually don't care about the function pointers themselves, we just need a way to build higher-order functions.

Maybe you missed it, but in my original post I actually said in the comments in the reproducer that the functor object would be my preferred solution :)

```c++
// Supporting templates would also be good (in fact even better for my usecase)
// template<class Func>
// double algo(Func func, double x) {}
```

So if my reproducer modified by using the template signature and not the function pointer would work, then this issue can be closed as well. That would be a big step for RooFit, because then we can use a lot of existing templated functions when generating the code for a RooFit model!

**Comment by vaithak** [comment]
Although differentiation of functor object inside a function body is supported in clad, there seems to be some issue with passing it as a parameter, looking into this.

**Comment by parth-07** [comment]
Hi @guitargeek,

> That's great news, since I actually don't care about the function pointers themselves, we just need a way to build higher-order functions.

Oh, that's great.

> Maybe you missed it, but in my original post I actually said in the comments in the reproducer that the functor object would be my preferred solution :)

Yes, I missed it :').

> So if my reproducer modified by using the template signature and not the function pointer would work, then this issue can be closed as well. 

We support functors as @vaithak mentioned. Please see the below code snippet for functor differentiation.

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

class Identity {
    public:
    double& operator()(double u) { return u; }
};

template<class F>
double algo(F f, double x) {
    double val = f(x);
    return val * val;
}

int main() {
    auto grad = clad::gradient(algo<Identity>);
    double x=3, dx=0;
    Identity di;
    grad.execute(Identity(), x, &di, &dx);
    show(dx); // This prints: x: 6
}
```

The above program works as expected. However, currently, if we change, `double& operator()(double u) { return u; }`
to `double operator()(double u) { return u; }` (non-reference return type), then the differentiation fails. This is
due to incorrect cloning of CXX operator overloads. This issue will be fixed soon.

**Comment by guitargeek** [comment]
Thanks!

> The above program works as expected. However, currently, if we change, `double& operator()(double u) { return u; }` to `double operator()(double u) { return u; }` (non-reference return type), then the differentiation fails. This is due to incorrect cloning of CXX operator overloads when we have non-reference return types. This issue will be fixed soon.

Can you maybe open a separate GitHub issue about this, so it will not be forgotten? Or is such an issue already open?
