### ISSUE TITLE
`multiple definition of trap(int)` link error occurs when multiple files contain `clad/Differentiator/Differentiator.h` header file

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#693]
Users have to include `clad/Differentiator/Differentiator.h` header file to run clad generated code because this header provides clad tape and clad array interface. It's likely that different files in a project may be using clad generated codes and thus will require including `Differentiator.h` header. However, linking two files containing `Differentiator.h` gives `multiple definition of trap(int)` error. This behaviour is unexpected and incorrect. A header file should not contain definitions that may lead to ODR violations. 

Reproducible example:

**reproduce.sh**
```
#!/usr/bin/env

cat >foo.c <<\EOF
#include "clad/Differentiator/Differentiator.h"

int foo() { return 1; }
EOF

cat >main.cpp <<\EOF
#include "clad/Differentiator/Differentiator.h"

int foo();

int main() { return foo(); }
EOF

/usr/lib/llvm-15/bin/clang++ -g -Xclang -add-plugin -Xclang clad \
    -Xclang -load -Xclang \
    /path/to/clad.so \
    -I/path/to/clad/include \
    main.cpp -xc++ -o main foo.cpp
```

```
bash -x ./reproduce.sh
```

**Comment by maxaehle** [comment]
When running your code with Clad at 1bdd261ea71163b3e8074dca4018e94a481a1c50 and Clang-11, I get the same "multiple definition" error as you and a few more errors, all related to symbols from the namespace `numerical_diff`; e.g., a function `printError(double, double, unsigned int, int)` and a variable `bufferManager`. 

I'm not sure whether you already have a plan on how to fix this, but I have encountered similar problems in the past (in other projects) so I'd like to share a couple of ideas how to fix it here.

For function definitions, I'm aware of the following ways to fix this:

**1. inline**: Declare the function as  `inline`. For C++ sources including the header, 
> There may be more than one definition of an inline function [...] in the program as long as each definition appears in a different translation unit and (for non-static inline functions [...]) all definitions are identical. For example, an inline function [...] may be defined in a header file that is included in multiple source files. 

according to [cppreference.com](https://en.cppreference.com/w/cpp/language/inline). For C sources including the header,

> The inline definition that does not use extern is not externally visible and does not prevent other translation units from defining the same function. This makes the inline keyword an alternative to static for defining functions inside header files, which may be included in multiple translation units of the same program. 

according to [cppreference.com](https://en.cppreference.com/w/c/language/inline).

**2. static**: Declare the function as `static`, so other translation units don't see the function.

For definitions of variables like `numerical_diff::bufferManager`, this is more difficult. As far as I know, `inline` variables only exist since C++17 (and not for C). You can declare a variable `static` but this means that it's a different copy in each translation unit, which might or might not be adequate for `bufferManager` (I don't know). 

**1. Define variable in source file**: Declare the variable as `extern` in the header, create a separate source file containing the definition (without `extern`), and have users supply the new source file to the clang call besides their own source files. Or compile the source file and let the user supply a `-l` flag to link it. This is not very convenient, but I guess it also works for C sources.

**2. Static member of some template instantiation**: A C++ "hack" to define global variables in header files is to use templates, as suggested in [this stackoverflow answer](https://stackoverflow.com/a/3229904). Specifically for `numerical_diff::bufferManager`, this would mean to replace the definition in NumericalDiff.h by 
```c++
template<int irrelevant>
struct helperTemplate {
  static ManageBufferSpace bufferManager;
};
template<int irrelevant>
ManageBufferSpace helperTemplate<irrelevant>::bufferManager;
```
and then use `helperTemplate<0>::bufferManager` instead of `bufferManager` in the remainder of the source code (it does not matter whether the constant `0` or any other `int` is used). Defining some helper
```c++
ManageBufferSpace& getBufferManager(){
  return helperTemplate<0>::bufferManager;
}
```
might be useful.

As a side note, while I'm not too familiar with the internals of Clad, I suspect that in order to differentiate some function, Clad needs its code and the code of all the functions potentially called by it (transitively) in a single translation unit.

**Comment by vgvassilev** [comment]
Thanks for the detailed report. I believe I have a fix that I can land hopefully today.
