### ISSUE TITLE
Re-enable tests on i568

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#792]
In PR #782 we have enabled support of 32 bit platforms and we have disabled many failing tests. Most of the failures are due to the fact that `sizeof` returns `unsigned int` on 32 bit and the test reference files require adjustment of that type:
`// CHECK-NEXT:     unsigned {{(int|long)}} _t2 = sizeof(double);`

**Comment by MihailMihov** [comment]
Could I work on this issue? And also is there any way to run the 32-bit tests locally?

**Comment by vgvassilev** [comment]
Go ahead. You can use a virtualization system like virtualbox or you can operate at the bot: https://clad.readthedocs.io/en/latest/user/DevelopersDocumentation.html#debugging-github-runners

**Comment by MihailMihov** [comment]
I got most of the tests running at https://github.com/MihailMihov/clad/tree/fix-32bit-tests, but I'm not sure if that's the correct way to solve the issue. Aren't the tests becoming somewhat weaker and maybe they'll fail to catch some regressions?
Looking at LLVM's FileCheck documentation there is an option [`--check-prefixes`](https://llvm.org/docs/CommandGuide/FileCheck.html#cmdoption-FileCheck-check-prefixes) to check multiple prefixes and maybe it would be possible to split the 32- and 64-bit checks, so that lit tests for the correct output on each architecture?
Also there are 3 tests which I haven't yet gotten to work ([FirstDerivative/Overloads](https://github.com/MihailMihov/clad/actions/runs/8349003628/job/22852198463), [Misc/ClangConsumers](https://github.com/MihailMihov/clad/actions/runs/8347739885/job/22848053603) and [Gradient/Pointers](https://github.com/MihailMihov/clad/actions/runs/8347429416/job/22847008577)). Could the segfault in the last one come from the CI environment not having kokkos?

**Comment by vgvassilev** [comment]
> I got most of the tests running at https://github.com/MihailMihov/clad/tree/fix-32bit-tests, but I'm not sure if that's the correct way to solve the issue. Aren't the tests becoming somewhat weaker and maybe they'll fail to catch some regressions?

If you mean that out of a sudden clang starts thinking that the size of a size_t is an int on 64 bit platforms, that's highly unlikely. If that happens many more things around the world will break first. The tests that are expected to test clad won't get weaker, however, if the tests intended to test clang that'd be correct.

> Looking at LLVM's FileCheck documentation there is an option [`--check-prefixes`](https://llvm.org/docs/CommandGuide/FileCheck.html#cmdoption-FileCheck-check-prefixes) to check multiple prefixes and maybe it would be possible to split the 32- and 64-bit checks, so that lit tests for the correct output on each architecture? 

We could but that's much more handwork work when we need to change them. I'd not do that.

> Also there are 3 tests which I haven't yet gotten to work ([FirstDerivative/Overloads](https://github.com/MihailMihov/clad/actions/runs/8349003628/job/22852198463), [Misc/ClangConsumers](https://github.com/MihailMihov/clad/actions/runs/8347739885/job/22848053603) and [Gradient/Pointers](https://github.com/MihailMihov/clad/actions/runs/8347429416/job/22847008577)). Could the segfault in the last one come from the CI environment not having kokkos?

What are the related stack traces?
