### ISSUE TITLE
Store the cmake invocation arguments on a file in the build directory

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#811]
This is a huge relief if one needs to reconfigure with the same invocation arguments. That also help bug reports as we can ask people to send their invocations over.

**Comment by sauravUppoor** [comment]
> This is a huge relief if one needs to reconfigure with the same invocation arguments.

@vgvassilev - I think I do not fully understand the advantage that this proposed file will serve. Isn't this why the CMake Cache is for - to avoid user having to enter the configs again. 

For bug reports, users can just send the `CMakeCache.txt` file which will be exhaustive list of all the user's config choices. If the user doesn't have the cache file, it is very much possible that they might also lose this proposed new file as both will reside in the `build` dir.

As for the solution, we can have a check for flags from a static list, assuming the user used the non-scripting mode of cmake as given in the installation guide (since it doesn't allow parsing the command line args). But again,  I feel the already existing cache will be more exhaustive and serve our purpose better.

**Comment by vgvassilev** [comment]
It's a matter of convenience: I need to be able to copy-paste the invocation line, that is, what the user has dialed on the terminal. The `CMakeCache` is does not let me do that. Here is an implementation approach: https://stackoverflow.com/questions/10205986/how-to-capture-cmake-command-line-arguments
