### ISSUE TITLE
Support for std::initializer_list

### ISSUE THREAD

**Issue by krathul** [vgvassilev/clad#830]
differentiating functions containing std::initializer_list shows the "Not supported" warning and throws error.
```c
int fn(int x) {
  int res = 0;
  auto &&range = {1, 2, 3};
  for (auto i = range.begin(); i != range.end(); i++) {
    res += x * (*i);
  }
  return res;
}
```

**Comment by Deepanshu9376** [comment]
I think because you're trying to use a range-based for loop with an std::initializer_list, which doesn't support non-const iterators.  Instead, you can iterate over the elements directly without using iterators.
Like this :-)
int fn(int x) {
  int res = 0;
  auto range = {1, 2, 3};
  for (auto val : range) {
    res += x * val;
  }
  return res;
}

**Comment by vgvassilev** [comment]
This depends on https://github.com/vgvassilev/clad/issues/724.
